apiVersion: v1
kind: Service
metadata:
  name: flask-keycloak-app-81
spec:
  selector:
    app: flask-keycloak-app-81
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort